# Generated by Django 2.1.7 on 2019-03-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete='cascade', related_name='students', to='basicapp.School'),
        ),
    ]
